<a href="https://colab.research.google.com/github/Kethellem/cursopython/blob/main/PreProcessamentoDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
from google.colab import files
uploaded = files.upload()

Saving TELECON.csv to TELECON.csv

In [6]:
#Importação de dados de acordo com o diretório
df = pd.read_csv('TELECON.csv', delimiter=';')
df.head(10)

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),NaN,1840.75,No
4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes
5,9305-CDSKC,NaN,0,No,No,8,Yes,Fiber optic,No,No,Yes,Month-to-month,Electronic check,NaN,820.50,NaN
6,1452-KIOVK,NaN,0,No,Yes,22,Yes,Fiber optic,No,No,Yes,Month-to-month,Credit card (automatic),NaN,1949.40,NaN
7,6713-OKOMC,NaN,0,No,No,10,No,DSL,Yes,No,No,Month-to-month,Mailed check,NaN,301.90,NaN
8,7892-POOKP,NaN,0,Yes,No,28,Yes,Fiber optic,No,Yes,Yes,Month-to-month,Electronic check,NaN,3046.05,NaN
9,6388-TABGU,NaN,0,No,Yes,62,Yes,dsl,Yes,No,No,One year,Bank transfer (automatic),NaN,3487.95,NaN

In [7]:
#Com esse comando conseguimos verificar qual o tipo de dados de cada coluna.
df.dtypes

customerID             object
Genero                 object
Idoso                   int64
Casado                 object
Dependents             object
Tempo_como_Cliente      int64
PhoneService           object
Servico_Internet       object
Servico_Seguranca      object
Suporte_Tecnico        object
StreamingTV            object
Tipo_Contrato          object
PaymentMethod          object
Pagamento_Mensal      float64
Total_Pago            float64
Churn                  object
dtype: object

In [8]:
#Este codigo retornará True se houver algum valor nulo em qualquer lugar do DataFrame, e False caso contrário.
df.isnull().values.any()

np.True_

In [9]:
# Contar o numero de valores nulos em cada coluna
df.isnull().sum()

customerID               0
Genero                  12
Idoso                    0
Casado                   0
Dependents               0
Tempo_como_Cliente       0
PhoneService          1482
Servico_Internet         0
Servico_Seguranca        0
Suporte_Tecnico          0
StreamingTV              0
Tipo_Contrato            0
PaymentMethod            0
Pagamento_Mensal       325
Total_Pago               0
Churn                    5
dtype: int64

PORCENTAGME DE DADOS FALTANTES

In [10]:
# Para contar o número de valores nulos em cada coluna
(df.isnull().sum() / len(df)) * 100

customerID             0.00
Genero                 0.48
Idoso                  0.00
Casado                 0.00
Dependents             0.00
Tempo_como_Cliente     0.00
PhoneService          59.28
Servico_Internet       0.00
Servico_Seguranca      0.00
Suporte_Tecnico        0.00
StreamingTV            0.00
Tipo_Contrato          0.00
PaymentMethod          0.00
Pagamento_Mensal      13.00
Total_Pago             0.00
Churn                  0.20
dtype: float64

COLUNA GENERO

Nessa coluna temos apenas 0.48% dos dados faltantes pouco para uma base tão grande

In [11]:
df[df['Genero'].isnull()]

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes
5,9305-CDSKC,NaN,0,No,No,8,Yes,Fiber optic,No,No,Yes,Month-to-month,Electronic check,NaN,820.50,NaN
6,1452-KIOVK,NaN,0,No,Yes,22,Yes,Fiber optic,No,No,Yes,Month-to-month,Credit card (automatic),NaN,1949.40,NaN
7,6713-OKOMC,NaN,0,No,No,10,No,DSL,Yes,No,No,Month-to-month,Mailed check,NaN,301.90,NaN
8,7892-POOKP,NaN,0,Yes,No,28,Yes,Fiber optic,No,Yes,Yes,Month-to-month,Electronic check,NaN,3046.05,NaN
9,6388-TABGU,NaN,0,No,Yes,62,Yes,dsl,Yes,No,No,One year,Bank transfer (automatic),NaN,3487.95,NaN
10,9763-GRSKD,NaN,0,Yes,Yes,13,Yes,dsl,Yes,No,No,Month-to-month,Mailed check,NaN,587.45,No
11,7469-LKBCI,NaN,0,No,No,16,Yes,No,No internet service,No internet service,No internet service,Two year,Credit card (automatic),NaN,326.80,No
12,8091-TTVAX,NaN,0,Yes,No,58,Yes,Fiber optic,No,No,Yes,One year,Credit card (automatic),NaN,5681.10,No
13,0280-XJGEX,NaN,0,No,No,49,Yes,Fiber optic,No,No,Yes,Month-to-month,Bank transfer (automatic),NaN,5036.30,Yes
14,5129-JLPIS,NaN,0,No,No,25,Yes,Fiber optic,Yes,Yes,Yes,Month-to-month,Electronic check,NaN,2686.05,No
15,3655-SNQYZ,NaN,0,Yes,Yes,69,Yes,Fiber optic,Yes,Yes,Yes,Two year,Credit card (automatic),NaN,7895.15,No

Excluindo valores faltantes da coluna Genero

In [12]:
# Excluindo
df.dropna(subset=['Genero'], inplace=True)
#InplaceTrue faz com que as alterações sejam feitas diretamente no DataFrame original

In [13]:
df['Genero'].isnull().sum()

np.int64(0)

a exclusão de dados faltantes na coluna Genero nao gera impacto na nossa base de dados já que a informação principal que queremos e Churn

COLUNA CustomerID

In [14]:
#Removendo coluna customerID
df.drop(columns=['customerID'], inplace=True)

Excluindo coluna customerID pois não são dados relevantes dentro do nosso modelo

COLUNA PHONESERVICE

preenchendo os nulos da coluna phoneservice com a moda (valor mais frequente)

In [22]:
# Encontrar o valor mais frequente (moda)
moda_PhoneService = df['PhoneService'].mode()

# Preencher os nulos com a moda
df['PhoneService'].fillna(moda_PhoneService, inplace=True)

In [23]:
# Verificando se ainda resta dandos faltantes
(df.isnull().sum() / len(df)) * 100

Genero                 0.000000
Idoso                  0.000000
Casado                 0.000000
Dependents             0.000000
Tempo_como_Cliente     0.000000
PhoneService           0.000000
Servico_Internet       0.000000
Servico_Seguranca      0.000000
Suporte_Tecnico        0.000000
StreamingTV            0.000000
Tipo_Contrato          0.000000
PaymentMethod          0.000000
Pagamento_Mensal      12.580386
Total_Pago             0.000000
Churn                  0.000000
dtype: float64

“Realizei o tratamento dos dados faltantes.
Na coluna PhoneService, os valores nulos foram preenchidos com o valor mais frequente encontrado no dataset.

COLUNA PAGAMENTO_MENSAL

Fazendo o tratamento dos dados da coluna pagamento_mensal com Média e Mediana para preencher o execesso de registros

In [36]:
# Analisando Média
df['Pagamento_Mensal'].mean()

np.float64(65.60756321839081)

In [25]:
# Analisando Mediana
df['Pagamento_Mensal'].median()

71.45

SUBISTITUINDO PELA MEDIANA

In [54]:
mediana_Pagamento_Mensal = df['Pagamento_Mensal'].median()
# Substituindo os valores faltantes na coluna de Pagamento Mensal
df['Pagamento_Mensal'].fillna(mediana_Pagamento_Mensal, inplace=True)

/tmp/ipython-input-54-4289848837.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Pagamento_Mensal'].fillna(mediana_Pagamento_Mensal, inplace=True)

In [55]:
df['Pagamento_Mensal'].isnull().sum()

np.int64(0)

In [57]:
# Verificando colunas se ainda possui dados faltantes
(df.isnull().sum() / len(df)) * 100

Genero                0.0
Idoso                 0.0
Casado                0.0
Dependents            0.0
Tempo_como_Cliente    0.0
PhoneService          0.0
Servico_Internet      0.0
Servico_Seguranca     0.0
Suporte_Tecnico       0.0
StreamingTV           0.0
Tipo_Contrato         0.0
PaymentMethod         0.0
Pagamento_Mensal      0.0
Total_Pago            0.0
Churn                 0.0
dtype: float64

Para a coluna Pagamento_Mensal, utilizei a mediana como forma de preenchimento, considerando que essa estratégia reduz impactos de possíveis outliers.


CORRIGINDO DADOS INCONSISTENTES

In [60]:
df['Servico_Internet'].unique()

In [62]:
#Transformando todos os dados da coluna Servico_Internet em caixa alta
df['Servico_Internet'] = df['Servico_Internet'].str.upper()

In [63]:
#Utilizando a função replace
df['Servico_Internet'] = df['Servico_Internet'].replace('DSL', 'DLS')

In [64]:
#Visualizando alterações
df['Servico_Internet'].unique()

array(['DLS', 'NO', 'FIBER OPTIC'], dtype=object)

Os dados errados foram subistituido pela correção em letras maiusculas utilizando o comando upper

PADRONIZANDO COLUNAS TODAS EM PORTUGUÊS

In [65]:
#Utilizando a função rename
df.rename(columns={'Dependents': 'Dependentes'}, inplace=True)
df.rename(columns={'PhoneService': 'Servico_Telefonico'}, inplace=True)
df.rename(columns={'StreamingTV': 'Transmissao_TV'}, inplace=True)
df.rename(columns={'PaymentMethod': 'Forma_Pagamento'}, inplace=True)

In [66]:
df.head()

,Genero,Idoso,Casado,Dependentes,Tempo_como_Cliente,Servico_Telefonico,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,Transmissao_TV,Tipo_Contrato,Forma_Pagamento,Pagamento_Mensal,Total_Pago,Churn
0,Female,0,Yes,No,1,No,DLS,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,DLS,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,DLS,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,DLS,Yes,Yes,No,One year,Bank transfer (automatic),71.45,1840.75,No
16,F,0,No,No,52,Yes,NO,No internet service,No internet service,No internet service,One year,Mailed check,71.45,1022.95,No